# Generated by Django 5.2.3 on 2025-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adresse', models.TextField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('vendu', 'Vendu')], default='disponible', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_biens/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
