# Generated by Django 5.2.3 on 2025-06-17 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens_possedes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='type_bien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biens.typebien'),
        ),
    ]
