# Generated by Django 5.2.3 on 2025-06-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='vendu',
            field=models.BooleanField(default=False),
        ),
    ]
