# Generated by Django 5.1.3 on 2025-06-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_transaction', models.CharField(choices=[('location', 'Location'), ('achat', 'Achat')], max_length=10)),
                ('prix_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(default='en attente', max_length=50)),
            ],
        ),
    ]
